bookers2-debug/config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end


   resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get "search" => "searches#search"
  
end

bookers2-debug/app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  
  validates :comment, presence: true
  
end

bookers2-debug/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    @book_comment = BookComment.new
    comment.book_id = @book.id
    if comment.save
      render :book_comments
    else
      redirect_to request.referer
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
    @book_comment = BookComment.new
    render :book_comments
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

bookers2-debug/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2-debug/app/views/book_comments/_book_comments.html.erb
<table class='table'>
<p><% book.book_comments.each do |book_comment| %>
  <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
  <%= book_comment.user.name %>
  </p>
  <p><%= book_comment.comment %></p>
  <% if book_comment.user == current_user %>
  <p><%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment),method: :delete, remote: true, class: "btn btn-sm btn-danger" %></p>
  <% end %>
<% end %>
 </table>

bookers2-debug/app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <%= f.text_area :comment, rows: '5' %>
  <%= f.submit"送信" %>
<% end %>

bookers2-debug/app/views/book_comments/book_comments.js.erb
$("#comments_area").html("<%= j(render 'book_comments/book_comments', book: @book) %>");

$("#new-comment").html("<%= j(render 'book_comments/form', book: @book, book_comment: @book_comment) %>");

$("textarea").val('');